### ISSUE TITLE
Add option to save logging history data to CSV file

### ISSUE THREAD

**Issue by kjetilgloppen** [kyma-as/api-dashboard#31]
Many customers are using CSV files for processing data collected by the KSP. Therefore, it would be a nice feature to give our API customers an easy way of downloading logging history for a given time period with a given granularity, directly to a CSV file. 

The UX might look something like the logging history selection on Kyma Online today:

![image](https://user-images.githubusercontent.com/16953738/57066815-94ad6d80-6ccd-11e9-9fd5-2103c660c028.png)

The CSV file should have a header with the variable names and unit (in parentheses). The first column should always be the time stamp:
`Time;Shaft Power (kW);Shaft Speed (rpm);Shaft Torque (kNm)
01.01.2019 00:00:00,000;10956,50136;63,74875754;1641,243956
01.01.2019 01:00:00,000;10981,26588;63,84538943;1642,460382
`

You can use the new API (currently undocumented) that gets the CSV file directly:
`https://kspoffice.kyma.no/api/v1/logdata/Find?logVariableId=3499&granularity=Day&fromDate=2016-09-01&toDate=2016-09-13&format=csv`

**Comment by tbkvamme** [comment]
Just to add:
The BatchFind endpoint is probably the best to use here:

    https://kspoffice.kyma.no/api/v1/logdata/BatchFind?logVariableIds=3499,3500,123,321&granularity=Day&fromDate=2016-09-01&toDate=2016-09-13&format=csv

Note the s in logVariableId**s**

**Comment by kjetilgloppen** [comment]
Good point if you want to get the CSV formatted text directly. But then we have a limit on 10 variables??

**Comment by tbkvamme** [comment]
yeah, 10 variables is max for BatchFind....we could of course increase it?
